services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django-docker-pblog
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./db:/app/db # If using SQLite, otherwise remove this

    env_file: .env.prod
    ports:
      - "8000:8000"  # Ensure the correct port mapping

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db: {}  # Fix volume declaration